# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(840, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("background-color:rgb(230, 230, 230)")
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 350, 600))
        self.widget.setStyleSheet("background-color: rgb(50, 67, 71);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.imgFilePathEdit = QtWidgets.QLineEdit(self.widget)
        self.imgFilePathEdit.setGeometry(QtCore.QRect(10, 30, 271, 31))
        self.imgFilePathEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.imgFilePathEdit.setText("")
        self.imgFilePathEdit.setObjectName("imgFilePathEdit")
        self.compressButton = QtWidgets.QPushButton(self.widget)
        self.compressButton.setGeometry(QtCore.QRect(10, 140, 331, 31))
        self.compressButton.setStyleSheet("background-color: rgb(50, 67, 71);\n"
"color: rgb(255, 255, 255);")
        self.compressButton.setObjectName("compressButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.quantitylSlider = QtWidgets.QSlider(self.widget)
        self.quantitylSlider.setGeometry(QtCore.QRect(10, 110, 271, 22))
        self.quantitylSlider.setProperty("value", 50)
        self.quantitylSlider.setOrientation(QtCore.Qt.Horizontal)
        self.quantitylSlider.setObjectName("quantitylSlider")
        self.quantityLabel = QtWidgets.QLabel(self.widget)
        self.quantityLabel.setGeometry(QtCore.QRect(310, 110, 31, 16))
        self.quantityLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.quantityLabel.setObjectName("quantityLabel")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 161, 191))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.oriFileInfotextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.oriFileInfotextBrowser.setGeometry(QtCore.QRect(10, 20, 141, 161))
        self.oriFileInfotextBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.oriFileInfotextBrowser.setObjectName("oriFileInfotextBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 180, 161, 191))
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.aftFileInfotextBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.aftFileInfotextBrowser.setGeometry(QtCore.QRect(10, 20, 141, 161))
        self.aftFileInfotextBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.aftFileInfotextBrowser.setObjectName("aftFileInfotextBrowser")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 331, 211))
        self.groupBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.logtextBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.logtextBrowser.setGeometry(QtCore.QRect(10, 20, 201, 181))
        self.logtextBrowser.setToolTip("")
        self.logtextBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.logtextBrowser.setObjectName("logtextBrowser")
        self.openFilePathButton = QtWidgets.QPushButton(self.groupBox_3)
        self.openFilePathButton.setGeometry(QtCore.QRect(214, 20, 111, 23))
        self.openFilePathButton.setObjectName("openFilePathButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(220, 50, 101, 121))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.githubButton = QtWidgets.QPushButton(self.groupBox_3)
        self.githubButton.setGeometry(QtCore.QRect(220, 180, 101, 23))
        self.githubButton.setObjectName("githubButton")
        self.selectImgButton = QtWidgets.QPushButton(self.widget)
        self.selectImgButton.setGeometry(QtCore.QRect(290, 30, 51, 31))
        self.selectImgButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.selectImgButton.setObjectName("selectImgButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(360, 10, 471, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.showOriImgLabel = QtWidgets.QLabel(self.groupBox_4)
        self.showOriImgLabel.setGeometry(QtCore.QRect(10, 20, 446, 251))
        self.showOriImgLabel.setObjectName("showOriImgLabel")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 310, 471, 281))
        self.groupBox_5.setObjectName("groupBox_5")
        self.showAftImgLabel = QtWidgets.QLabel(self.groupBox_5)
        self.showAftImgLabel.setGeometry(QtCore.QRect(10, 20, 446, 251))
        self.showAftImgLabel.setObjectName("showAftImgLabel")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JPEG COMPRESSOR"))
        self.label.setText(_translate("MainWindow", "图像路径："))
        self.imgFilePathEdit.setPlaceholderText(_translate("MainWindow", "图像文件的绝对路径..."))
        self.compressButton.setText(_translate("MainWindow", "开始压缩"))
        self.label_2.setText(_translate("MainWindow", "质量因子："))
        self.quantityLabel.setText(_translate("MainWindow", "50%"))
        self.groupBox.setTitle(_translate("MainWindow", "原始文件："))
        self.oriFileInfotextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件路径：</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件大小：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">创建时间：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">修改时间：</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "生成文件："))
        self.aftFileInfotextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件路径：</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件大小：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">创建时间：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">修改时间：</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "日志："))
        self.logtextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">...</p></body></html>"))
        self.openFilePathButton.setText(_translate("MainWindow", "打开生成路径"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "本程序适用于初步压缩以无损格式储存的图像文件（如BMP，PNG）并以JPG格式储存"))
        self.githubButton.setText(_translate("MainWindow", "Github "))
        self.selectImgButton.setText(_translate("MainWindow", "打开"))
        self.groupBox_4.setTitle(_translate("MainWindow", "原始图："))
        self.showOriImgLabel.setText(_translate("MainWindow", "原始图像显示区域"))
        self.groupBox_5.setTitle(_translate("MainWindow", "生成图："))
        self.showAftImgLabel.setText(_translate("MainWindow", "生成图像显示区域"))
import resource_rc
